name: Steps examples
on:
  workflow_dispatch:
jobs:
  steps_examples:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir testmachine
      - run: uname -a > output.txt
      - run: cat output.txt
      - run: ls -alhR
      
