name: Uses Examples
on:
  workflow_dispatch:
jobs:
  user_examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: install Python requirements
        uses: aabadie/action-install-python-requirements@v2.0.1
      - name: run script
        run: python my_script.py
